### ISSUE TITLE
Chinesisch: Use Case und Zielgruppe?

### ISSUE THREAD

**Issue by wschmidle** [dainst/special-character-input#1]
Was soll bei Chinesisch der Use Case und die Zielgruppe sein? Jeder, der Chinesisch lesen kann, hat auch ein Eingabe-System (IME) installiert/aktiviert.

Die Zeichenliste ist zurzeit einfach ein Stück eines besonders harmlosen Bereichs von chinesischen Zeichen in Unicode (CJK Unified Ideographs), und dann alle hintereinander weg. Insbesondere nichts jenseits von U+FFFF, wo es beginnt interessant zu werden, ob Systeme damit umgehen können. Und selbst wenn man nur mit diesen paar Zeichen schreiben will, ist das nicht praktisch. Soll man sich der Unicode-Nicht-Reihenfolge nach durch die Tafeln blättern? 

Das Widget wird außerdem unten abgeschnitten.

**Comment by dersmon** [comment]
Abschneiden könnte daran liegen, dass dein Bildschirm etwas kleiner ist, wenn das bei der Verwendung laufend ein Problem ist, müsste man die Gruppe ggf. in zwei aufteilen. 

Wenn man mehr oder komplett andere Zeichen haben möchte, muss man entsprechend die JSON umkonfigurieren.

**Comment by dersmon** [comment]
Der Use Case sind entsprechend die Bibliotheken: Die haben das nicht unbedingt installiert, wollen aber manchmal Titel aufnehmen mit exotischeren Schriftzeichen.

**Comment by dersmon** [comment]
Die JSON ist entsprechend eine Beispielkonfiguration. In Kategorienauswahl, deren Umfang und Reihenfolge.

**Comment by wschmidle** [comment]
Der Punkt ist, dass dieser Ansatz für Chinesisch nicht skaliert, und ich sehe auch keine einfache Möglichkeit, wie das korrigiert werden kann. Sobald man eine realistische Anzahl von chinesischen Zeichen hat, braucht man eine sinnvollere Anordnung als die Zeichen in der Unicode-Reihenfolge aufzuzählen. Zum Beispiel eine Suche über Pinyin oder Radikal wie bei https://ctext.org/dictionary.pl?if=en oder (für den kleineren japanischen Zeichensatz) https://mpi-lingweb.shh.mpg.de/kanji/ (und dann links unter "Graphemliste"). Und selbst damit ist es schwierig, wenn man es nicht lesen kann. Wie wahrscheinlich ist es, dass man ein Zeichen dann richtig eingegeben hat? Frag am besten mal eine/n Bibliothekar/in, der/die tatsächlich regelmäßig chinesische Zeichen eingibt.

Ich sehe leider als einzige Lösung, die chinesische Eingabemethode ersatzlos zu streichen.

**Comment by dersmon** [comment]
Wie gesagt, die Beispielkonfiguration kann man anpassen und chineisch ggf. rauswerfen oder anpassen wenn man damit nicht arbeiten kann. Das Repo soll nur die Möglichkeit geben, im Web direkt Zeichen einzufügen, die man nicht auf der eigenen Tastatur hat.

**Comment by dersmon** [comment]
Oder anders ausgedrückt: Theoretisch könntest du dir hier auch eine Emoji Eingabe basteln. Es soll wirklich nicht ein IME ersetzen.

**Comment by wschmidle** [comment]
Ich versuche es nochmal möglichst klar zu formulieren: Chinesisch ist ein Beispiel, das mit diesem Ansatz nicht funktioniert und auch nie funktionieren wird. Deshalb sollte es nicht im Beispiel-JSON in diesem Repository stehen.

**Comment by wschmidle** [comment]
Ich würde es deshalb jetzt entfernen, wenn's recht ist.

**Comment by dersmon** [comment]
Hau rein. :wink:
